fullnameOverride: llama-coder

model:
  path: /models/Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf
  name: Qwen2.5-Coder-7B-Instruct-Q4_K_M
  contextSize: 4096

tolerations:
  - key: node.longhorn.io/storage
    operator: Exists
    effect: NoSchedule

nodeSelector:
  kubernetes.io/hostname: pi4-node01.home.mowntan.com

persistence:
  models:
    nfs:
      server: synology-nas01.home.mowntan.com
      path: /volume2/downloads/models
