fullnameOverride: llama-llama

model:
  path: /models/Llama-3.2-3B-Instruct-Q4_K_M.gguf
  name: "Fast (Llama-3.2-3B)"
  contextSize: 4096

tolerations:
  - key: node.longhorn.io/storage
    operator: Exists
    effect: NoSchedule

nodeSelector:
  kubernetes.io/hostname: pi4-node03.home.mowntan.com

persistence:
  models:
    nfs:
      server: synology-nas01.home.mowntan.com
      path: /volume2/downloads/models
