apiVersion: v1
entries:
  llama-cpp:
  - apiVersion: v2
    appVersion: b8340
    created: "2026-03-14T22:05:56.52490772Z"
    description: llama.cpp single-node inference, OpenAI-compatible HTTP API
    digest: 9590d9847299acfb71761bfecaacb44e91a35f4e4733883de7de05bafa183f58
    name: llama-cpp
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/llama-cpp-2.0.0.tgz
    version: 2.0.0
  ollama:
  - apiVersion: v2
    appVersion: 0.17.0
    created: "2026-03-14T22:05:56.52526853Z"
    description: Ollama local large language model server
    digest: 46ade18bff3edff2d7d02c9bbdfdac7bf7c8ff803f96226c5664aae19e3bdefe
    name: ollama
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/ollama-1.0.0.tgz
    version: 1.0.0
  open-webui:
  - apiVersion: v2
    appVersion: 0.8.3
    created: "2026-03-14T22:05:56.525511194Z"
    description: Open WebUI for Ollama
    digest: ac8d64effc523ce37b55c86a1c86df7dbbdbf4be513aefe19c8fc11c3b2a2d75
    name: open-webui
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/open-webui-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-14T22:05:56.524406297Z"
