apiVersion: v1
entries:
  llama-cpp:
  - apiVersion: v2
    appVersion: b8148
    created: "2026-02-26T22:03:35.276380633Z"
    description: llama.cpp distributed inference with RPC multi-node support
    digest: 2c62eddd29e17944fe5a5ed070e6181c2fef1f5686bcf06e3beb6889444eadc6
    name: llama-cpp
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/llama-cpp-1.0.1.tgz
    version: 1.0.1
  ollama:
  - apiVersion: v2
    appVersion: 0.17.0
    created: "2026-02-26T22:03:35.276795253Z"
    description: Ollama local large language model server
    digest: 90524132336a9cb6e7250189d55107a371e96b18fded8ef14d59318871a1d285
    name: ollama
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/ollama-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-26T22:03:35.275857949Z"
