apiVersion: v1
entries:
  llama-cpp:
  - apiVersion: v2
    appVersion: b8148
    created: "2026-03-01T04:37:34.804286045Z"
    description: llama.cpp single-node inference, OpenAI-compatible HTTP API
    digest: 5992026863d99ab5e1a8a075a76d171a294e745b7e363d00620b05dd9f655d7c
    name: llama-cpp
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/llama-cpp-2.0.0.tgz
    version: 2.0.0
  ollama:
  - apiVersion: v2
    appVersion: 0.17.0
    created: "2026-03-01T04:37:34.804688101Z"
    description: Ollama local large language model server
    digest: 042400e1ad20ccb8ed73bbe04f68576a89ac1e4bd3f802b6e17b59323594342f
    name: ollama
    type: application
    urls:
    - https://mowntan.github.io/k8s-ai-lab/charts/ollama-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-01T04:37:34.803794183Z"
