nodeSelector:
  kubernetes.io/arch: arm64
  node-role.kubernetes.io/homelab: ""

persistence:
  models:
    enabled: false

webui:
  enabled: true
  env:
    - name: OLLAMA_BASE_URL
      value: ""
    - name: OPENAI_API_BASE_URLS
      value: "http://llama-coder:8080/v1;http://llama-mistral:8080/v1;http://llama-llama:8080/v1;http://llama-phi:8080/v1"
    - name: OPENAI_API_KEYS
      value: "none;none;none;none"
  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: chat.apps.mowntan.com
        paths:
          - path: /
            pathType: Prefix
