nodeSelector:
  kubernetes.io/arch: arm64
  node-role.kubernetes.io/homelab: ""

env:
  - name: OLLAMA_BASE_URL
    value: ""
  - name: OPENAI_API_BASE_URLS
    value: "http://llama-coder.ai-lab.svc:8080/v1;http://llama-phi.ai-lab.svc:8080/v1"
  - name: OPENAI_API_KEYS
    value: "none;none"
  - name: WEBUI_AUTH
    value: "true"

persistence:
  enabled: true
  storageClass: longhorn
  size: 2Gi

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: chat.apps.mowntan.com
      paths:
        - path: /
          pathType: Prefix
